import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider, Layout } from "antd";
import { Header } from "antd/es/layout/layout";
import Title from "antd/es/typography/Title";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              borderRadius: 10,
            },
          }}
        >
          <Layout>
            <Header
              style={{
                borderBottom: "1px solid #e8e8e8",
                width: "100%",
                textAlign: "left",
                boxShadow: "0 1px 0px 0 #f0f0f0, 0 1px 0px 0 #f0f0f0",
                backgroundColor: "white",
              }}
            >
              <Title>Socast</Title>
            </Header>
          </Layout>
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
