version: '3'
services:
  gpodder-service:
    container_name: gPodder
    build:
      context: ./micro-gpodder-server
      dockerfile: Dockerfile
    volumes:
      - ./micro-gpodder-server/docker_volume:/var/www/html/
    hostname: 192.168.178.70
    ports:
      - 3005:80

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "3000:3000"
#    depends_on:
#      - gpodder-service
#    volumes:
#      - ./backend:/app
#      - /app/node_modules##

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3001"
#    depends_on:
#      - backend
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
