version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    depends_on:
      - gpodder-service
  gpodder-service:
    image: gpodder2go
    ports:
    - "3005:3005"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend 