version: '3'
services:
  gpodder-service:
    image: gpodder2go
    ports:
    - "3005:3005"
    volumes:
      - ./gpodder/g2g.db:/gpodder2go/g2g.db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"  
    depends_on:
      - gpodder-service
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules